### ISSUE TITLE
LDBC enhancement

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula-bench#54]
1. using fixed_string vid, and each tag with a unique id, e.g. Person: 123456 -> p123456 or person123456
2. split tag. e.g. place splits to 3 tags, city, country, continent
3. and then change the importer schema

**Comment by wenhaocs** [comment]
don't forget to use the newest version of importer and k6

**Comment by HarrisChu** [comment]
sure
also would add a doc for https://github.com/vesoft-inc/nebula-bench/blob/master/scripts/env.sh

**Comment by czpmango** [comment]
> using fixed_string vid, and each tag with a unique id, e.g. Person: 123456 -> p123456 or person123456

Also keep ID(such as Person.id) as attribute to preserve some procession freedom.
FEG: https://github.com/ldbc/ldbc_snb_interactive/blob/d8cf3632d925873127043b777f6e64da15f2c9a9/cypher/queries/interactive-complex-5.cypher#L1-L30

**Comment by HarrisChu** [comment]
https://github.com/vesoft-inc/nebula-bench/pull/63
